/**
 * RBAC (Role-Based Access Control) Core Definition & Permission Engine
 * Primary Roles: SUPER_ADMIN > EVENT_ADMIN > ORGANIZER > STAFF
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  EVENT_ADMIN: 'EVENT_ADMIN',
  ORGANIZER: 'ORGANIZER',
  STAFF: 'STAFF'
};

const ROLE_LEVELS = {
  [ROLES.SUPER_ADMIN]: 4,
  [ROLES.EVENT_ADMIN]: 3,
  [ROLES.ORGANIZER]: 2,
  [ROLES.STAFF]: 1
};

// Normalize role strings from tokens or legacy inputs
function normalizeRole(roleStr) {
  if (!roleStr) return ROLES.STAFF;
  const upper = roleStr.toUpperCase().replace(/\s+/g, '_');
  if (upper.includes('SUPER') || upper === 'ADMIN') return ROLES.SUPER_ADMIN;
  if (upper.includes('EVENT_ADMIN') || upper.includes('EVENT_MANAGER') || upper.includes('COORDINATOR')) return ROLES.EVENT_ADMIN;
  if (upper.includes('ORGANIZER') || upper.includes('LOGISTICS')) return ROLES.ORGANIZER;
  if (upper.includes('STAFF') || upper.includes('VENDOR') || upper.includes('CREW')) return ROLES.STAFF;
  return ROLES.STAFF;
}

// Permission Matrix Check
const PERMISSIONS = {
  // User Management
  MANAGE_EVENT_ADMINS: [ROLES.SUPER_ADMIN],
  CREATE_EVENT_ADMIN: [ROLES.SUPER_ADMIN],
  MANAGE_ALL_USERS: [ROLES.SUPER_ADMIN],
  MANAGE_SCOPED_ORGANIZERS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  MANAGE_SCOPED_STAFF: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  
  // Event Operations
  CREATE_EVENT: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  MANAGE_ALL_EVENTS: [ROLES.SUPER_ADMIN],
  MANAGE_SCOPED_EVENTS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  ASSIGN_ORGANIZER_TO_EVENT: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  UPDATE_ASSIGNED_EVENT_OPERATIONS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER],
  VIEW_ASSIGNED_EVENT: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER, ROLES.STAFF],
  DELETE_EVENT: [ROLES.SUPER_ADMIN],

  // Resource & Staff Allocations
  OVERRIDE_ALL_RESOURCES: [ROLES.SUPER_ADMIN],
  ALLOCATE_EVENT_RESOURCES: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  ASSIGN_EVENT_STAFF: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER],
  REQUEST_EVENT_EQUIPMENT: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER],
  VIEW_RESOURCES: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER, ROLES.STAFF],

  // Tasks Management
  CREATE_EVENT_TASKS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER],
  ASSIGN_TASKS_TO_STAFF: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER],
  UPDATE_OWN_TASKS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN, ROLES.ORGANIZER, ROLES.STAFF],

  // System & Telemetry
  SYSTEM_SETTINGS: [ROLES.SUPER_ADMIN],
  GLOBAL_AUDIT_LOGS: [ROLES.SUPER_ADMIN],
  SCOPED_AUDIT_LOGS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN],
  SYSTEM_REPORTS: [ROLES.SUPER_ADMIN, ROLES.EVENT_ADMIN]
};

function hasPermission(userRole, permissionKey) {
  const normRole = normalizeRole(userRole);
  const allowed = PERMISSIONS[permissionKey];
  return allowed ? allowed.includes(normRole) : false;
}

module.exports = {
  ROLES,
  ROLE_LEVELS,
  PERMISSIONS,
  normalizeRole,
  hasPermission
};
